- name: Remove Taint in all master Node
  become: yes
  become_user: kubernetes
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  environment:
    KUBECONFIG: /home/kubernetes/.kube/config

- name: Create Nginx Deployment
  become_user: kubernetes
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        namespace: default
        name: nginx-deployment
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
              - name: nginx-container
                image: jcohenp/dcoya:latest
                ports:
                  - containerPort: 443
    kubeconfig: /home/kubernetes/.kube/config

- name: Expose Nginx Deployment
  become_user: kubernetes
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        namespace: default
        name: dcoya-nginx
      spec:
        selector:
          app: nginx
        ports:
          - protocol: TCP
            port: 443
            targetPort: 443
            nodePort: 30000
        type: NodePort
    kubeconfig: /home/kubernetes/.kube/config
