- name: Install Kubernetes
  hosts: kubernetes-nodes
  tasks:

  - name: Install pip3 on Debian-based systems
    become: true
    apt:
      name: python3-pip
      state: present

  - name: Install the 'kubernetes' Python package
    become: true
    pip:
      name: kubernetes
      executable: pip3

  - name: Add Google official GPG key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Add Kubernetes Repository
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes
      mode: 0600

  - name: Install kubeadm, kubelet, and kubectl
    become: true
    apt:
      name: ['kubelet=1.21.1-00','kubeadm=1.21.1-00','kubectl=1.21.1-00']
      state: present
      allow_downgrades: yes

  - name: Initialize Kubernetes cluster
    become: true
    command: kubeadm init --pod-network-cidr=10.244.0.0/16

  - name: Ensure the .kube directory exists
    file:
      path: /home/ubuntu/.kube
      state: directory
      mode: '0755'
      owner: ubuntu

  - name: Copy kubeconfig to user's home directory
    become: true
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ubuntu/.kube/config
      remote_src: yes
      owner: ubuntu

  - name: Install Calico CNI
    become: true
    command: kubectl apply -f https://docs.projectcalico.org/archive/v3.14/manifests/calico.yaml
    environment:
      KUBECONFIG: /home/ubuntu/.kube/config

  - name: Include Nginx role
    include_role:
      name: nginx
