- name: Install Kubernetes
  hosts: kubernetes-nodes
  tasks:
  - name: Install pip3 on Debian-based systems
    become: true
    apt:
      name: python3-pip
      state: present

  - name: Install the 'kubernetes' Python package
    become: true
    pip:
      name: kubernetes
      executable: pip3

  - name: Add Google official GPG key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Add Kubernetes Repository
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes
      mode: 0600

  - name: Install kubeadm, kubelet, and kubectl
    become: true
    apt:
      name: ['kubelet=1.21.1-00','kubeadm=1.21.1-00','kubectl=1.21.1-00']
      state: present
      allow_downgrades: yes

  - name: Create kubernetes user
    user:
      name: kubernetes
      shell: /bin/bash
      create_home: yes

  - name: Add kubernetes to sudoers
    lineinfile:
      dest: /etc/sudoers
      line: 'kubernetes ALL=(ALL) NOPASSWD:/usr/bin/kubectl, /usr/bin/kubeadm'
      validate: 'visudo -cf %s'
      insertafter: EOF
      state: present


  - name: Initialize Kubernetes cluster
    become_user: root
    become: true
    command: kubeadm init --pod-network-cidr=10.244.0.0/16

  - name: Ensure the .kube directory exists
    file:
      path: /home/kubernetes/.kube
      state: directory
      mode: '0755'
      owner: kubernetes

  - name: Copy kubeconfig to user's home directory
    become: true
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/kubernetes/.kube/config
      remote_src: yes
      owner: kubernetes
      mode: '0660'

  - name: Install Calico CNI
    become: true
    command: kubectl apply -f https://docs.projectcalico.org/archive/v3.14/manifests/calico.yaml
    environment:
      KUBECONFIG: /home/kubernetes/.kube/config

  - name: Add execute permission to the script
    become: yes
    file:
      path: chrome.sh
      mode: u+x

  - name: install chrome browser 
    become: yes
    command: "./chrome.sh"

  - name: Copy folder for the kubernetes user
    become_user: root
    command: "cp -R /home/ubuntu/dcoya_challenge/ /home/kubernetes"
  
  - name: change ownership to the kubernetes user
    become_user: root
    command: "chown -R kubernetes: /home/kubernetes/dcoya_challenge"


  - name: Include Nginx role
    include_role:
      name: nginx
